version: '3.8'

  
networks:
  network:
    driver: bridge  

      
services:


  #MYSQL DataBase
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network
  
  #Backend (Laravel)
  api:
    build: ./api
    container_name: api
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - network
    volumes:
      - ./api:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  #Frontend (Nuxt.js)
  client:
    build: ./client
    container_name: client
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - network

  #Proxy Server      
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    ports:
      - "443:443" #HTTPS Port
    networks:
      - network
    depends_on:
      - api
      - client        



volumes:
  db_data:

