version: '3.8'

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16  # Define the subnet for the network
          gateway: 172.18.0.1  # Optional: Set the gateway IP
          
services:
  # MYSQL DataBase
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      network:
        ipv4_address: 172.18.0.2  # Valid static IP address
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # Backend (Laravel)
  api:
    build: ./api
    container_name: api
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: 172.18.0.2
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      network:
        ipv4_address: 172.18.0.3  # Valid static IP address
    volumes:
      - ./api:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # Frontend (Nuxt.js)
  client:
    build: ./client
    container_name: client
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      network:
        ipv4_address: 172.18.0.4  # Valid static IP address
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # Proxy Server      
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    ports:
      - "443:443" # HTTPS Port
    networks:
      network:
        ipv4_address: 172.18.0.5  # Valid static IP address
    depends_on:
      - api
      - client
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  db_data:
