version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  api:
    build: ./api
    container_name: api
    volumes:
      - ./api:/var/www
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: laravelpass
    networks:
      - app-network
    depends_on:
      - db

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - api
      - client

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
